# Generated by Django 4.0.3 on 2022-11-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_combo', models.CharField(max_length=40)),
                ('preco_combo', models.CharField(max_length=40)),
                ('itens_combo', models.TextField()),
                ('pessoas', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=40)),
                ('preco_item', models.IntegerField()),
                ('valor_promocional', models.IntegerField()),
                ('ingredientes', models.TextField()),
                ('descricao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.categoria')),
            ],
        ),
    ]
