# Generated by Django 4.0.3 on 2022-11-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_item_img_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='itens',
            field=models.ManyToManyField(blank=True, null=True, to='cardapio.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default=False, upload_to='templates/media'),
        ),
    ]
