# Generated by Django 4.0.3 on 2022-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alter_carrinho_itens_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
