# Generated by Django 4.0.3 on 2022-11-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_alter_carrinho_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='itens',
            field=models.ManyToManyField(blank=True, to='cardapio.item'),
        ),
    ]
