# Generated by Django 4.0.3 on 2022-11-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_alter_carrinho_id_alter_carrinho_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='itens',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Item_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.carrinho')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.item')),
            ],
        ),
    ]
