# Generated by Django 4.0.3 on 2022-11-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_remove_carrinho_itens_carrinho_pago_item_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco_item',
            field=models.FloatField(),
        ),
    ]
