# Generated by Django 4.0.3 on 2022-12-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_alter_item_valor_promocional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='pago',
        ),
    ]
