# Generated by Django 4.0.3 on 2023-01-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0010_remove_carrinho_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valor_promocional',
            field=models.FloatField(blank=True),
        ),
    ]
