# Generated by Django 4.0.3 on 2023-01-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0014_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='templates/media'),
        ),
    ]
