# Generated by Django 4.0.3 on 2023-01-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0016_alter_item_disponivel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disponivel_item',
            field=models.BooleanField(null=True),
        ),
    ]
