# Generated by Django 4.0.3 on 2023-01-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0017_alter_item_disponivel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disponivel_item',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
