# Generated by Django 4.0.3 on 2023-01-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0018_alter_item_disponivel_item_alter_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='templates/media'),
        ),
    ]
