# Generated by Django 4.0.3 on 2023-03-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0025_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vitrine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='../media/default.jpg', upload_to='imagens_item'),
        ),
    ]
