# Generated by Django 4.0.3 on 2023-03-02 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0028_alter_carrinho_user_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='user_carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
