# Generated by Django 4.0.3 on 2023-03-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0030_alter_carrinho_user_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='user_carrinho',
        ),
    ]
