# Generated by Django 4.0.3 on 2023-03-02 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapio', '0031_remove_carrinho_user_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='user_carrinho',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
