# Generated by Django 4.0.3 on 2022-12-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
