# Generated by Django 4.0.3 on 2022-12-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func_mode', '0002_alter_pedido_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='func_mode.status'),
            preserve_default=False,
        ),
    ]
