# Generated by Django 4.0.3 on 2022-12-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_mode', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
