# Generated by Django 4.0.3 on 2022-12-31 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func_mode', '0007_remove_pedido_status_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='func_mode.status'),
            preserve_default=False,
        ),
    ]
