# Generated by Django 4.0.3 on 2022-10-19 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('admin', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=70)),
                ('num', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('ref', models.TextField()),
                ('bairro', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
