# Generated by Django 4.0.3 on 2022-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_endereco_delete_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telefone',
            field=models.IntegerField(blank=True),
        ),
    ]
