# Generated by Django 4.0.3 on 2023-03-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func_mode', '0009_alter_pedido_cliente'),
        ('home', '0003_alter_account_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='conta',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
